apiVersion : apps/v1
kind: Deployment
metadata:
  name: project1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1 
    spec:
      containers:
        - name: project1 
          image: katuricontainerregistry.azurecr.io/project1
          ports:
          - containerPort: 80